src/Shark.AuthorizationServer/Controllers/DeviceAuthorizeController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Shark.AuthorizationServer.Core.Abstractions.ApplicationServices;
using Shark.AuthorizationServer.Core.Responses.DeviceAuthorize;
using Shark.AuthorizationServer.Mappers;
using Shark.AuthorizationServer.Requests;

namespace Shark.AuthorizationServer.Controllers;

[Route("[controller]")]
[ApiController]
public sealed class DeviceAuthorizeController(
    IDeviceAuthorizeApplicationService deviceAuthorizeApplicationService) : ControllerBase
{
    private readonly IDeviceAuthorizeApplicationService _deviceAuthorizeApplicationService = deviceAuthorizeApplicationService;

    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<IActionResult> Post([FromForm] DeviceAuthorizeRequest request)
    {
        var internalResponse = await _deviceAuthorizeApplicationService.Execute(request.ToInternalRequest());

        switch (internalResponse)
        {
            case DeviceAuthorizeResponse response:
                return Ok(response);
            default:
                return new StatusCodeResult((int)HttpStatusCode.NotImplemented);
        }
    }
}

src/Shark.AuthorizationServer/Pages/Device.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shark.AuthorizationServer.Core.Abstractions.Services;

namespace Shark.AuthorizationServer.Pages;

public sealed class DeviceModel(IDeviceService deviceService) : PageModel
{
    private const string UserCodeData = nameof(UserCodeData);

    private readonly IDeviceService _deviceService = deviceService;

    public string? UserCode { get; set; }

    public async Task<IActionResult> OnGet([FromQuery(Name = "user_code")] string userCode)
    {
        if (!string.IsNullOrEmpty(userCode))
        {
            return await RedirectToDeviceAuthorizePage(userCode);
        }

        return Page();
    }

    public async Task<IActionResult> OnPost(string userCode)
    {
        if (!string.IsNullOrEmpty(userCode))
        {
            return await RedirectToDeviceAuthorizePage(userCode);
        }

        return RedirectToPage("Error");
    }

    private async Task<IActionResult> RedirectToDeviceAuthorizePage(string userCode)
    {
        if (await _deviceService.ValidateUserCode(userCode))
        {
            TempData[UserCodeData] = userCode;
            return RedirectToPage("DeviceAuthorize");
        }

        ModelState.AddModelError("UserCode", "Invalid code");

        return Page();
    }
}

src/Shark.AuthorizationServer/Pages/Device/Device.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shark.AuthorizationServer.Core.Abstractions.Services;

namespace Shark.AuthorizationServer.Pages.Device;

public sealed class DeviceModel(IDeviceService deviceService) : PageModel
{
    private const string UserCodeData = nameof(UserCodeData);

    private readonly IDeviceService _deviceService = deviceService;

    [Required]
    public string? UserCode { get; set; }

    public async Task<IActionResult> OnGet([FromQuery(Name = "user_code")] string userCode)
    {
        if (!string.IsNullOrEmpty(userCode))
        {
            return await RedirectToDeviceAuthorizePage(userCode);
        }

        return Page();
    }

    public async Task<IActionResult> OnPost(string userCode)
    {
        if (ModelState.IsValid)
        {
            if (!string.IsNullOrEmpty(userCode))
            {
                return await RedirectToDeviceAuthorizePage(userCode);
            }
        }

        return RedirectToPage("Error");
    }

    private async Task<IActionResult> RedirectToDeviceAuthorizePage(string userCode)
    {
        if (await _deviceService.ValidateUserCode(userCode))
        {
            TempData[UserCodeData] = userCode;
            return RedirectToPage("DeviceAuthorize");
        }

        ModelState.AddModelError("UserCode", "Invalid code");

        return Page();
    }
}

src/Shark.AuthorizationServer/Pages/Device/DeviceAuthorize.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shark.AuthorizationServer.Core.Abstractions.Services;

namespace Shark.AuthorizationServer.Pages.Device;

public sealed class DeviceAuthorizeModel(IDeviceService deviceService) : PageModel
{
    private const string UserCodeData = nameof(UserCodeData);
    private const string SuccessData = nameof(SuccessData);

    private readonly IDeviceService _deviceService = deviceService;

    public async Task<IActionResult> OnPostAuthorize()
    {
        await _deviceService.Authorize(GetUserCode());

        TempData[SuccessData] = true;
        return RedirectToPage("DeviceAuthorizeComplete");
    }

    public async Task<IActionResult> OnPostDeny()
    {
        await _deviceService.Deny(GetUserCode());

        TempData[SuccessData] = false;
        return RedirectToPage("DeviceAuthorizeComplete");
    }

    private string? GetUserCode()
    {
        var userCode = TempData[UserCodeData] as string;
        TempData[UserCodeData] = null;

        return userCode;
    }
}

src/Shark.AuthorizationServer/Pages/Device/DeviceAuthorizeComplete.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Shark.AuthorizationServer.Pages.Device;

public sealed class DeviceAuthorizeCompleteModel : PageModel
{
    private const string SuccessData = nameof(SuccessData);

    public bool Success { get; private set; }

    public void OnGet()
    {
        Success = Convert.ToBoolean(TempData[SuccessData]);
    }
}

src/Shark.AuthorizationServer/Pages/DeviceAuthorize.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shark.AuthorizationServer.Core.Abstractions.Services;

namespace Shark.AuthorizationServer.Pages;

public sealed class DeviceAuthorizeModel(IDeviceService deviceService) : PageModel
{
    private const string UserCodeData = nameof(UserCodeData);
    private const string SuccessData = nameof(SuccessData);

    private readonly IDeviceService _deviceService = deviceService;

    public async Task<IActionResult> OnPostAuthorize()
    {
        await _deviceService.Authorize(GetUserCode());

        TempData[SuccessData] = true;
        return RedirectToPage("DeviceAuthorizeComplete");
    }

    public async Task<IActionResult> OnPostDeny()
    {
        await _deviceService.Deny(GetUserCode());

        TempData[SuccessData] = false;
        return RedirectToPage("DeviceAuthorizeComplete");
    }

    private string? GetUserCode()
    {
        var userCode = TempData[UserCodeData] as string;
        TempData[UserCodeData] = null;

        return userCode;
    }
}

src/Shark.AuthorizationServer/Pages/DeviceAuthorizeComplete.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Shark.AuthorizationServer.Pages;

public sealed class DeviceAuthorizeCompleteModel : PageModel
{
    private const string SuccessData = nameof(SuccessData);

    public bool Success { get; private set; }

    public void OnGet()
    {
        Success = Convert.ToBoolean(TempData[SuccessData]);
    }
}

src/Shark.AuthorizationServer/Pages/Device/Device.cshtml
@page "/device"
@model DeviceModel
@{
    ViewData["Title"] = "OAuth Authorization Server";
}

<div class="text-center">
    <h1 class="display-5">Shark OAuth Authorization Server</h1>
    <p>Enter the code displayed on the screen of your device</p>

    <form method="post">
        <div class="form-group">
            @Html.TextBoxFor(m =>
                @Model.UserCode,
                new { @class = "form-input", placeholder = "Enter user code", required = "required", maxlength = 6 })
            <br />
            <span asp-validation-for="UserCode" class="text-danger"></span>
        </div>
        <br />
        <input type="submit" value="Submit" />
    </form>
</div>

src/Shark.AuthorizationServer/Pages/Device/DeviceAuthorize.cshtml
@page
@model DeviceAuthorizeModel
@{
    ViewData["Title"] = "OAuth Authorization Server";
}
<style>
    form {
        display: inline-block;
        margin-right: 10px;
    }
</style>

<div class="text-center">
    <h1 class="display-5">Shark OAuth Authorization Server</h1>
    <p>Authorize your device for the cliet application</p>

    <form method="post" asp-page-handler="Authorize">
        <input type="submit" value="Authorize" />
    </form>

    <form method="post" asp-page-handler="Deny">
        <input type="submit" value="Deny" />
    </form>
</div>

src/Shark.AuthorizationServer/Pages/Device/DeviceAuthorizeComplete.cshtml
@page
@model DeviceAuthorizeCompleteModel
@{
    ViewData["Title"] = "OAuth Authorization Server";
}
<style>
    form {
        display: inline-block;
        margin-right: 10px;
    }
</style>

<div class="text-center">
    <h1 class="display-5">Shark OAuth Authorization Server</h1>
    @if (@Model.Success)
    {
        <div>
            <h4 class="red">Your device has been successfully authorized</h4>
            <p>
                You can now enjoy full access to all features and services without any restrictions.
                For your security, this authorization ensures that only recognized devices can interact
                with your account. If you did not initiate this authorization, or if you notice any
                unusual activity, please contact our support team immediately to secure your account.
            </p>
        </div>
    }
    else
    {
        <div>
            <h4 class="green">Your device was denied authorization.</h4>
            <p>
                Unfortunately, this device will not have access to the requested features or services.
                If you believe this was an error or need further assistance, don't hesitate to contact
                our support team to resolve the issue. Your security is our priority, and we are here
                to help keep your account safe.
            </p>
        </div>
    }
</div>